export interface ITheme {
    color0: string,
    color1: string,
    color2: string,
    color3: string,
    color4: string,
    color5: string,
    color6: string,
    color7: string,
    color8: string,
    color9: string,
    iconSize0: number,
    iconSize1: number,
    iconSize2: number,
    priorColor1: string,
    priorColor2: string,
    priorColor3: string,
    priorColor4: string,
    priorColor5: string,
    priorColor6: string,
    priorColor7: string,
    priorColor8: string,
    priorColor9: string,
}

export const themeDefault: ITheme = {
    color0: '#586FBE',
    color1: '#FFFFFF',
    color2: '#485DA2',
    color3: '#CCD2E8',
    color4: '#E5E4E5',
    color5: '#D6D5D6',
    color6: '#8FB7D6',
    color7: '#A0DEF0',
    color8: '#F6B57B',
    color9: '#F87652',
    iconSize0: 16,
    iconSize1: 18,
    iconSize2: 20,
    priorColor1: '#1231F7',
    priorColor2: '#4879F4',
    priorColor3: '#74B7F2',
    priorColor4: '#A0DEF0',
    priorColor5: '#EDFAED',
    priorColor6: '#F4E9C9',
    priorColor7: '#F6B57B',
    priorColor8: '#F87652',
    priorColor9: '#FD0013',
}