export interface ITheme {
    color0: string,
    color1: string,
    color2: string,
    color3: string,
    color4: string,
    color5: string,
    color6: string,
    color7: string,
    color8: string,
    color9: string,
    iconSize0: number,
    iconSize1: number,
    iconSize2: number,
}

export const themeDefault: ITheme = {
    color0: '#586FBE',
    color1: '#FFFFFF',
    color2: '#485DA2',
    color3: '#CCD2E8',
    color4: '#E5E4E5',
    color5: '#D6D5D6',
    color6: '#8FB7D6',
    color7: '',
    color8: '',
    color9: '#000000',
    iconSize0: 16,
    iconSize1: 16,
    iconSize2: 16,
}